# Topics in Econometrics and Data Science: Tutorial 3

#### General Note

You will very likely find the solution to these exercises online. We, however, strongly encourage you to work on these exercises without doing so. Understanding someone else’s solution is very different from coming up with your own. Use the lecture notes and try to solve the exercises independently.

## Exercise 1: Linear Algebra with `NumPy` 

Make sure that you have installed the module *numpy* by

In [1]:
import numpy as np

Let us consider the matrix $X$

In [2]:
X=np.matrix([[2,3,4],[9,33,5],[3,12,35],[23,16,2]])
print(X)

[[ 2  3  4]
 [ 9 33  5]
 [ 3 12 35]
 [23 16  2]]


There are different methods for matrices that can be applied column or row-wise. For example, one can calculate the column-sums by

In [3]:
print(X.sum(0))

[[37 64 46]]


Enter the follwing arrays in Python (matrices and vectors):

$A = \begin{bmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{bmatrix}$

$x = \begin{bmatrix}
1\\ 
3\\ 
4
\end{bmatrix}$

$B = \begin{bmatrix}
-0.1 & -0.2 & -0.3\\ 
3 & 10 & 2\\ 
4 & 2 & 0.5
\end{bmatrix} $

a) Calculate the row-sums of matrix $A$

b) Calculate the mean of each column in matrix $B$:

Perform the following operations:

c) $A \bullet B$ (matrix multiplication)

d) $A \bullet x$

e) $A \circ B$ (element-wise multiplication) Hint: np.array()

## Exercise 2: Working with `NumPy` Arrays 

Your cell-phone bill varied the last year from month to month the following way

$$ 22\ 31\ 18\ 35\ 29 \ 32\ 19\ 23\ 23\ 25\ 20\ 33$$

* What is the largest amount you spent in a month? What is the smallest? 

* Find the total amount and the average amount per month that you spent in the last year!

* How many months was the amount greater than 30$? 

* Is it worth to enter into a flatrate (25$ per month) for the next year expecting on average the same bills?

## Exercise 3: Linear Regression with `NumPy`
The linear regression is a basic concept in statistics. Consider the linear regression model
$$
y_i = \beta_0 + \beta_1X_i + \varepsilon_i 
$$
One can estimate the coefficients $\mathbf{\hat{\beta}}$ by solving the following matrix equation:
$$
\boldsymbol{\hat{\beta}}=(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{y}
$$
Calculate $\boldsymbol{\hat{\beta}}$ and the residuals $\boldsymbol{\varepsilon} = \mathbf{y} - \mathbf{\hat{y}}$ using `NumPy` for the following small dataset.


| Shoe Size ($X$) | Height ($y$) |
|----------------|-------------|
|  36             |  170         |
|  37             |  175         |
|  38             |  180         |
|  38             |  169         |
|  40             |  190         |


* **Hint**: To have an intercept $\hat{\beta}_0$ in the model, just add a full column of $1s$ to your independent variable $X$ to get your design matrix $\mathbf{X}$ with `np.ones()` .